services:
  ${SERVICE_NAME}:
    container_name: ${SERVICE_NAME}
    image: uniclienttechnologies/${SERVICE_NAME}:latest
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - '/var/www/uploads:/uploads'
      - './logs:/app/logs'
    env_file:
      - ./environments/${NODE_ENV}.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    restart: always
    networks:
      - wagehat-net

networks:
  wagehat-net:
    driver: bridge
